export const ITEM_IMAGES: Record<string, string> = {
  // Starters
  'tuna-tartare':          '🐟',
  'burrata-salad':         '🧀',
  'chicken-wings':         '🍗',
  // Mains
  'spicy-chicken-sandwich': '🌶️',
  'classic-bistro-burger':  '🍔',
  'wagyu-smash-burger':     '🥩',
  'truffle-mushroom-burger':'🍄',
  'grilled-salmon':         '🐠',
  'caesar-salad-chicken':   '🥗',
  'veggie-grain-bowl':      '🥙',
  'bbq-pulled-pork':        '🥪',
  // Legacy burger IDs (keep for backward compat)
  'classic-burger':         '🍔',
  'spicy-chicken':          '🌶️',
  'mushroom-burger':        '🍄',
  'vegan-burger':           '🌱',
  'bbq-burger':             '🥩',
  // Sides
  'truffle-fries':          '🍟',
  'sweet-potato-fries':     '🍠',
  'caesar-side':            '🥬',
  'onion-rings':            '🧅',
  'mac-cheese':             '🧀',
  'coleslaw':               '🥗',
  'side-salad':             '🥗',
  // Drinks
  'still-water':            '🫗',
  'sparkling-water':        '💧',
  'fresh-lemonade':         '🍋',
  'iced-tea':               '🍵',
  'craft-cola':             '🥤',
  'mango-lassi':            '🥭',
  'root-beer-float':        '🍺',
  'classic-soda':           '🥤',
  'lemonade':               '🍋',
  'large-water':            '🫗',
  // Desserts
  'warm-brownie':           '🍫',
  'vanilla-cheesecake':     '🍰',
  'gelato-2-scoops':        '🍨',
  'apple-crumble':          '🍎',
};
